version : '3'
services :
  backend :
    build :
      context : .
    ports :
      - 5000:5000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: test@123
      MYSQL_DB: two_tier
  mysql :
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: test@123
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops
      MYSQL_DATABASE: two_tier
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:

       
